#!/bin/bash

echo "🚂 Deploying Layover App to Railway..."
echo ""

# Navigate to project root
cd "$(dirname "$0")"

echo "✅ Project linked to Railway"
echo ""

echo "📋 Next steps to complete deployment:"
echo ""
echo "1. Go to https://railway.com/project/4caaf3ef-e886-492a-96be-83462fbbe1e3"
echo ""
echo "2. Click '+ New' → 'GitHub Repo' → Select 'canboigay/layover-app'"
echo ""
echo "3. Configure BACKEND service:"
echo "   - Set Root Directory: backend"
echo "   - Add variables:"
echo "     NODE_ENV=production"
echo "     (Railway will auto-add REDIS_URL)"
echo ""
echo "4. Click '+ New' → 'GitHub Repo' again → Select 'canboigay/layover-app'"
echo ""
echo "5. Configure FRONTEND service:"
echo "   - Set Root Directory: frontend"
echo ""
echo "6. After both deploy, update env vars:"
echo ""
echo "   BACKEND:"
echo "   - CORS_ORIGIN=<frontend-url>"
echo "   - APP_URL=<frontend-url>"
echo ""
echo "   FRONTEND:"
echo "   - VITE_API_URL=<backend-url>/api"
echo "   - VITE_SOCKET_URL=<backend-url>"
echo ""
echo "7. Redeploy both services"
echo ""
echo "✨ Your app will be live!"
echo ""
